apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  labels:
    run: {{ .Values.name }}
spec:
  ports:
    - port: {{ .Values.port }}
      targetPort: {{ .Values.port }}
      protocol: TCP
  selector:
    app: {{ .Values.name }}
