services:
  mader_database:
    image: postgres
    env_file:
      - ./backend/.env
    volumes:
      - pgdata:/var/lib/postgresql/data

  mader_app:
    build: ./backend/
    image: mader_app
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 5s
      retries: 10
    entrypoint: ./entrypoint.sh
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/migrations:/app/migrations
    depends_on:
      - mader_database

  vue_app:
    build: ./frontend/
    image: vue_app
    ports:
      - "8080:80"
    depends_on:
      - mader_app

volumes:
  pgdata:

