services:
  database:
    image: postgres
    env_file:
      - ./backend/.env
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend/
    image: mader_app
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 5s
      retries: 10
    image: backend
    entrypoint: ./entrypoint.sh
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/migrations:/app/migrations
    depends_on:
      - database
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend/
    image: frontend
    ports:
      - "8080:8080"
    depends_on:
      - backend

volumes:
  pgdata:
