apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-db-secret
type: Opaque
data:
  db-name: {{ .Values.secrets.dbName | b64enc }}
  db-user: {{ .Values.secrets.dbUser | b64enc }}
  db-password: {{ .Values.secrets.dbPassword | b64enc }}
