apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-backend-secret
type: Opaque
data:
  secret-key: {{ .Values.secrets.secretKey | b64enc }}
  algorithm: {{ .Values.secrets.algorithm | b64enc }}
  access-token-expire-minutes: {{ .Values.secrets.accessTokenExpireMinutes | b64enc }}
  database-url: {{ .Values.secrets.dbUrl | b64enc }}
