apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-gateway-ingress
  namespace: {{ .Values.global.namespace }}
  annotations:
    spec.ingressClassName: nginx
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.global.backend.name }}
                port:
                  number: {{ .Values.global.backend.port }}
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.global.frontend.name }}
                port:
                  number: {{ .Values.global.frontend.port }}
