ingress:
  host: madr.local

service:
  port: 80

global:
  namespace: madr
  backend:
    name: backend
    port: 8000
  frontend:
    name: frontend
    port: 80
  database:
    name: database
    port: 5432
